version: '2'
services:
  nginx:
    image: "nginx:1.10.2"
    container_name: highload-nginx
    restart: always
    volumes:
      - /tmp:/tmp
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: "host"

  fastcgi:
    build: .
    restart: always
    container_name: highload-fastcgi
    volumes:
      - /tmp:/tmp
      - ./config/fastcgi:/app/config
    command: ["fastcgi-daemon2", "--config=/app/config/fastcgi.conf"]
    network_mode: "host"

  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    container_name: highload-mongo
    network_mode: "host"
